Tienda/Tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.sckates.urls')),
    #paths de recuperacion de contraseñas
    path('recuperacion-contraseña',auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('recuperacion-contraseña/continuar',auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('recuperacion-contraseña-confirmar/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('recuperacion-contraseña-exitoso',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

]

Tienda/apps/sckates/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = "sckates"

router = routers.DefaultRouter()
router.register(r'api/users', views.UsuariosViewSet)

urlpatterns = [
    

    url(r'^$', views.home, name="home"),
    url(r'^listar-clientes$', views.listar_clientes, name="cliente.listar"),
    path('editar-cliente/<int:idCliente>', views.editar_cliente, name="cliente.editar"),
    path('borrar-cliente/<int:idCliente>', views.borrar_cliente, name="cliente.borrar"),
    url(r'^agregar-cliente$', views.agregar_cliente, name="cliente.agregar"),
    
    url(r'^logout$', views.logout_account, name="logout"),
    url(r'^login$', views.login_account, name="login"),
    url(r'^', include(router.urls)),
    url(r'^ruedas', views.ruedas, name="ruedas"),
    url(r'^tablas', views.tablas, name="tablas"),
    url(r'^trucks', views.trucks, name="trucks"),

]

Tienda/apps/sckates/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


# Create your models here.


class Usuario(AbstractUser):
    pass
    image = models.ImageField(null=True, upload_to="images/usuarios")


    def __str__(self):
        return self.username
    
    def getImageUrl(self):
        #images/usuarios/Imagen_de_usuario.jpg
        return "static/" + str(self.image)

Tienda/apps/sckates/forms.py
from django import forms
from .views import *
from .models import *
from .widget import ImageWidget

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, help_text='Obligatorio. Ingresa tu nombre de usuario', label="Nombre de usuario")
    first_name = forms.CharField(max_length=30, required=True, help_text='Obligatorio. Ingresa tu nombre.', label="Nombre")
    last_name = forms.CharField(max_length=30, required=True, help_text='Obligatorio. Ingresa tu(s) apellido(s)', label="Apellido(s)")
    email = forms.EmailField(max_length=254, required=True, help_text='Obligatorio. Ingresa tu dirección de correo electrónico', label="Correo electrónico")
    password1 = forms.CharField(max_length=30, required=True, help_text='Obligatorio. Ingresa tu contraseña, debe ser una contraseña segura.', label="Contraseña")
    password2 = forms.CharField(max_length=30, required=True, help_text='Obligatorio. Re-ingresa tu contraseña, esta debe ser identica al campo anterior.', label="Confirmar contraseña")
    image = forms.ImageField(required=True, label="Foto actual:")

    username.widget = forms.TextInput(attrs={'class':'form-control'})
    first_name.widget = forms.TextInput(attrs={'class':'form-control'})
    last_name.widget = forms.TextInput(attrs={'class':'form-control'})
    email.widget = forms.TextInput(attrs={'class':'form-control'})
    password1.widget = forms.PasswordInput(attrs={'class':'form-control'})
    password2.widget = forms.PasswordInput(attrs={'class':'form-control'})
    image.widget = ImageWidget()
    class Meta:
        model = Usuario
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'image')

Tienda/apps/sckates/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required, user_passes_test
from rest_framework import viewsets
from .serializers import UsuarioSerializer

def home(request):
    return render(request, 'home.html')

def ruedas(request):
    return render(request, 'paginas/ruedas/rueda1.html')

def tablas(request):
    return render(request, 'paginas/tablas/tabla1.html')

def trucks(request):
    return render(request, 'paginas/trucks/truck.html')



def agregar_cliente(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES or None)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('sckates:cliente.listar')
    else:
        form = SignUpForm()

    return render(request, 'cliente/form-cliente.html', {'form':form})

@login_required
def listar_clientes(request):
    users = Usuario.objects.all()
    return render(request, "cliente/listar_clientes.html", {'clientes': users})

@login_required
def editar_cliente(request, idCliente):
    user = Usuario.objects.get(id=idCliente)
    form = SignUpForm(request.POST or None, request.FILES or None, instance=user) #CUANDO PASAS ALGUN ARCHIVO DEBE SER ASI (request.POST or None, request.FILES or None, instance=instance)

    if form.is_valid():
        form.save()
        return redirect('sckates:cliente.listar')

    return render(request, "cliente/form-cliente.html",{'form':form})   

@user_passes_test(lambda u: u.is_superuser)
def borrar_cliente(request, idCliente):    
    user= Usuario.objects.get(id=idCliente)
    user.delete()
    return redirect('sckates:cliente.listar')   
 
@login_required 
def logout_account(request):
    logout(request)
    return redirect('sckates:home')

def login_account(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        
        user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)
            return redirect('sckates:cliente.listar')

    return render(request, 'login.html')

class UsuariosViewSet(viewsets.ModelViewSet):
    queryset = Usuario.objects.all()
    serializer_class = UsuarioSerializer

Tienda/apps/sckates/templates/cliente/form-cliente.html
{% extends 'layout.html' %}

{% block content %}
    <section class="container">
        <div class="contenedor">
            <h1>Para agregar un cliente, complete el siguiente formulario</h1>

            <form method="POST" class="form ml-4" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            <small style="color:gray">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <small style="color:red">{{ error }}</small>
                        {% endfor %}
                    </div>
                {% endfor%}
                    
                <button type="submit" class="btn btn-sm btn-success">Guardar</button>
                <button type="reset"  class="btn btn-sm btn-primary">Limpiar</button>
            </form>
        </div>
    </section>
{% endblock %}

Tienda/apps/sckates/templates/cliente/listar_clientes.html
{% extends 'layout.html' %}
{% load staticfiles %}


{% block content %}
<main class="container">

    <section>
        <div class="contenedor">
            <h1>Lista de clientes</h1>   
        </div>
    </section>
    <div class="contenedor">
        <table class="table">
            <thead>
                <tr><!--Fila/Row-->
                    <th>
                        #
                    </th>
                    <th>
                        Nombre de usuario
                    </th>
                    <th>
                        Nombre Completo
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Imagen
                    </th>
                    <th>
                        Ultimo 
                        acceso
                    </th>
                    <th>
                        Es 
                        Staff
                    </th>
                    <th>
                        Es 
                        Activo
                    </th>
                    <th>
                        Fecha
                        Registro
                    </th>
                    <th>
                        {% if user.is_superuser %}  
                            Acciones
                        {% endif %}   
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for c in clientes %}
                    <tr>
                        <td>
                            {{c.id}}
                        </td>
                        <td>
                            {{c.username}}
                        </td>
                        <td>
                            {{ c.first_name}} {{c.last_name}}
                        </td>
                        <td>
                            {{ c.email}}
                        </td>
                        <td>
                            <img src="{{ c.getImageUrl }}" alt="foto de perfil" style="max-width:200px;height:100px;">
                        </td>  
                        <td>
                            {{ c.last_login}}
                        </td>    
                        <td>
                            {{ c.is_staff}}
                        </td>       
                        <td>
                            {{ c.is_active}}
                        </td>    
                        <td>
                            {{ c.date_joined}}
                        </td>   
                        <td>
                            {% if user.is_superuser %}
                            <a href="{% url 'sckates:cliente.editar' idCliente=c.id %}" class="btn btn-sm btn-primary"> Editar</a>
                            <a href="{% url 'sckates:cliente.borrar' idCliente=c.id %}" class="btn btn-sm btn-danger"
                            onclick="return confirm('¿Esta seguro de borrar?');"
                            > Borrar</a>
                            {% endif %}
                        </td>                                                                    
                    </tr>
                {% endfor %}
            </tbody>
        </table>         
        <form action="#" method="POST">
            Filtrar por Nombre            
            <input type="submit" value="Filtrar">
            {% csrf_token %}
         </form>  
         <form action="#" method="POST">
            Filtrar por fecha de registro            
            <input type="submit" value="Filtrar">
            {% csrf_token %}
         </form> 
         <form action="#" method="POST">
            Filtrar por ultimo acceso           
            <input type="submit" value="Filtrar">
            {% csrf_token %}
         </form> 
    </div>
    
</main>
{% endblock %}

Tienda/apps/sckates/templates/home.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block content %}

<section>
    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <!--Primera Slide-->
                    <img class="first-slide img-fluid" src="{% static 'images/25years_insta2_2.jpg' %}" alt="tablas element">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1>Las mejores tablas</h1>
                            <p><a class="btn btn-lg btn-primary" href="{% url 'sckates:cliente.agregar'%}"
                                    role="button">Registrate ahora</a></p>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <!--Segunda Slide-->
                    <img class="second-slide img-fluid"
                        src="{% static 'images/spitfire-ruedas-skate-full-conical-formula-4-56mm-laminate-D_NQ_NP_782206-MLC27270706507_042018-F.jpg'%}"
                        alt="trucks">
                </div>
                <div class="item">
                    <!--Tercera Slide-->
                    <img class="third-slide img-fluid" src="{% static 'images/1369119247-67926100.jpg'%}" alt="ruedas">
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>
<section>
    <article class="articulo1">
        <div class="container">
            <div class="contenedor">
                <H1>Registrate</H1>

                <p class="lead">para obtener descuento de 10% registrate!!
                </p>
                <a class="btn btn-primary btn-lg active" href="{% url 'sckates:cliente.agregar'%}">registrate</a>
            </div>
        </div>
    </article>

</section>
<section>
    <article class="articulo2">
        <div class="container">
            <div class="contenedor">
                <H1>Productos</H1>
                <div class="productos">
                    <div class="row">
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                <img src="{% static 'images/BDLGMLBP_DZD_1.jpg'%}" alt="...">
                                <div class="caption">
                                    <h3>Tabla Element</h3>
                                    <p>$39.990</p>
                                    <p><a href="{% url 'sckates:tablas' %}" class="btn btn-primary"
                                            role="button">Detalles</a> </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                <img src="{% static 'images/trucks.jpg'%}" alt="...">
                                <div class="caption">
                                    <h3>Truck Independent</h3>
                                    <p>$35.000</p>
                                    <p><a href="{% url 'sckates:trucks' %}" class="btn btn-primary"
                                            role="button">Detalles</a> </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                <img src="{% static 'images/1369119247-67926100.jpg'%}" alt="...">
                                <div class="caption">
                                    <h3>Ruedas SpitFire</h3>
                                    <p>$24.990</p>
                                    <p><a href="{% url 'sckates:ruedas' %}" class="btn btn-primary"
                                            role="button">Detalles</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </article>
</section>

{% endblock %}

Tienda/apps/sckates/templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="eS">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>INICIO SKTV</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- CSS -->
    <link href="{% static 'css/start.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>

<body>
    {% block header %}
    <header>
        <div class="navbar-wrapper">
            <div class="container">
                <nav class="navbar navbar-inverse navbar-static-top">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand navbar-image" href="#">sktv</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="/">Home</a></li>
                            <li><a href="agregar-cliente">Registro</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                    aria-haspopup="true" aria-expanded="false">Productos <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'sckates:tablas' %}">Tablas</a></li>
                                    <li><a href="{% url 'sckates:trucks' %}">Trucks</a></li>
                                    <li><a href="{% url 'sckates:ruedas' %}">Ruedas</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            {% if user.is_authenticated %}
                        <div>
                            <li><a href="{% url 'sckates:cliente.listar' %}">Usuario :{{user.username}}</a></li>
                            
                            <li><a href="{% url 'sckates:logout' %}">Cerrar Sesión</a></li>
                        </div>
                        {% else %}
                            <div>
                                <a href="{% url 'sckates:login' %}">Iniciar Sesión</a>
                            </div>
                        {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    
    <footer>
        <div class="container">
            <div class="contenedor">
                <div class="footer-copyright text-center">© 2018 Copyright:DUOC
                </div>
                <!-- Copyright -->
            </div>
        </div>
    </footer>
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

Tienda/apps/sckates/templates/login.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Iniciar Sesión</title>

    <link href="{% static 'css/bootstrap4.css' %}" rel="stylesheet">
</head>
<body>
    
    <main class="container">
        <section class="row justify-content-center mt-5">
            <div class="col-md-5">
                <div class="card">
                        <div class="card-header text-center">
                            <h5 class="card-title">Iniciar sesión</h5>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="username">Nombre de usuario</label>
                                    <input type="text" name="username" id="username" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="password">Contraseña</label>
                                    <input type="password" name="password" id="password" class="form-control">
                                </div>
        
                                <div class="text-center">
                                    <button type="submit" class="btn btn-sm btn-success">Iniciar Sesión</button>
                                    <div class="border-top pt-3">
                                        <small class="text-muted">
                                            <a class="ml-2" href="{% url 'password_reset' %}">Olvide mi contraseña</a>
                                        </small>
        </div>

                                </div>
                                
                            </form>
                        </div>
                    </div>
            </div>
            
        </section>
    </main>

</body>
</html>

Tienda/apps/sckates/templates/paginas/ruedas/rueda1.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block content %}

<section>
        <article class="articulo2">
            <div class="container">
                <div class="contenedor">
                    <div class="row transitionfx">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="detalleProducto">
                                <div class="main-image sp-wrap col-lg-12 no-padding">
                                    <a href="#">
                                        <img src="/static/images/650w_Rueda-street-53mm.jpg"
                                            class="img-responsive" alt="img">
                                    </a>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-5">
                            <div class="detalleProducto">
                                <h1> Ruedas 58mm</h1>
                                <h2>Codigo Producto : ava2202</h2>
                                <h3>$25.990</h3>
                                <div class="descripcion">
                                    <h4>Detalles Productos:</h4>
                                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, enim
                                    voluptates! Consequuntur numquam repudiandae quos accusamus dolor dignissimos
                                    cupiditate necessitatibus saepe, laboriosam, quod ad. Facere, ea aspernatur? Illo,
                                    vel similique?
                                </div>
                                <div class="cart-actions">
                                    <div class="text-center">
                                        <button type="button" class="btn btn-lg btns">Comprar</button>
                                    </div>
                                    <h3><i class="glyphicon glyphicon-lock"></i> Compra Segura
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>

{% endblock %}

Tienda/apps/sckates/templates/paginas/tablas/tabla1.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block content %}

 <section>
        <article class="articulo2">
            <div class="container">
                <div class="contenedor">
                    <div class="row transitionfx">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="detalleProducto">
                                <div class="main-image sp-wrap col-lg-12 no-padding">
                                    <a href="#">
                                        <img src="/static/images/BDLGMLBP_DZD_1.jpg"
                                            class="img-responsive" alt="img">
                                    </a>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-5">
                            <div class="detalleProducto">
                                <h1>Tabla Element 8.5</h1>
                                <h2>Codigo Producto : eba3301</h2>
                                <h3>$39.990</h3>
                                <div class="descripcion">
                                    <h4>Detalles Productos:</h4>
                                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, enim
                                    voluptates! Consequuntur numquam repudiandae quos accusamus dolor dignissimos
                                    cupiditate necessitatibus saepe, laboriosam, quod ad. Facere, ea aspernatur? Illo,
                                    vel similique?
                                </div>
                                <div class="cart-actions">
                                    <div class="text-center">
                                        <button type="button" class="btn btn-lg btns">Comprar</button>
                                    </div>
                                    <h3><i class="glyphicon glyphicon-lock"></i> Compra Segura
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>

{% endblock %}

Tienda/apps/sckates/templates/paginas/trucks/truck.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block content %}
<section>
        <article class="articulo2">
            <div class="container">
                <div class="contenedor">
                    <div class="row transitionfx">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="detalleProducto">
                                <div class="main-image sp-wrap col-lg-12 no-padding">
                                    <a href="#">
                                        <img src="/static/images/trucks.jpg" class="img-responsive" alt="img">
                                    </a>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-5">
                            <div class="detalleProducto">
                                <h1> Trucks Independent</h1>
                                <h2>Codigo Producto : cicada9963</h2>
                                <h3>$43.990</h3>
                                <div class="descripcion">
                                    <h4>Detalles Productos:</h4>
                                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, enim
                                    voluptates! Consequuntur numquam repudiandae quos accusamus dolor dignissimos
                                    cupiditate necessitatibus saepe, laboriosam, quod ad. Facere, ea aspernatur? Illo,
                                    vel similique?
                                </div>
                                <div class="cart-actions">
                                    <div class="text-center">
                                        <button type="button" class="btn btn-lg btns">Comprar</button>
                                    </div>
                                    <h3><i class="glyphicon glyphicon-lock"></i> Compra Segura
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    </section>
{% endblock %}